baseURL = 'https://ovenlydelights.shop/'
languageCode = 'en-us'
title = "Christmas Plum Cake - Ovenly Delights"

[params]
  description = "Order our signature Rich Fruit & Nut Christmas Plum Cake. Rum-soaked dried fruits, premium nuts, and aromatic spices. Small-batch, made to order."
  author = "Saumya"
  keywords = ["christmas plum cake", "plum cake", "fruit cake", "christmas cake", "rum cake", "homemade plum cake", "plum cake bangalore", "christmas cake bangalore", "order plum cake bangalore"]
  ogImage = "/assets/plum-cake-1.jpg"

disableKinds = ["taxonomy", "term"]
